export const content = {
  bdBadge: "For International Patients",
  hero: {
    headline: "Considering Heart or Cardiac Treatment in India?",
    subheadline:
      "Explore cardiac treatment options with experienced specialists and leading hospitals in India. Share your medical reports and let TrueCare help coordinate the next steps.",
    ctaPrimary: "Share Your Medical Reports",
    ctaSecondary: "Chat on WhatsApp",
    trustPoints: [
      "Cardiac Specialist Coordination",
      "Leading Hospital Network",
      "International Patient Support",
      "Clear Treatment Guidance",
    ],
  },
  trustStrip: {
    title: "Why patients choose TrueCare",
    items: [
      { title: "Cardiac Specialist Coordination", desc: "We help connect your case with the relevant cardiac specialist and hospital team." },
      { title: "Advanced Heart-Care Options", desc: "Explore options across interventional cardiology, cardiac surgery, valve care, and related specialties." },
      { title: "International Patient Assistance", desc: "Support with hospital communication, appointments, and the practical parts of your journey." },
      { title: "Clear Next Steps", desc: "Understand what information is needed and what happens after you submit your reports." },
    ],
  },
  howItWorks: {
    title: "Get Started in 3 Simple Steps",
    steps: [
      {
        title: "Share Your Reports",
        desc: "Submit recent medical reports, imaging, ECG/echo/cardiac investigation results, and basic case information securely.",
      },
      {
        title: "Case Coordination",
        desc: "TrueCare coordinates your case with the relevant hospital and cardiac specialist team.",
      },
      {
        title: "Understand Your Options",
        desc: "Receive information from the hospital about the recommended evaluation, treatment options, next steps, and estimated costs where available.",
      },
    ],
    note: "TrueCare coordinates your case. Medical evaluation, diagnosis, treatment recommendations, and clinical decisions are made by qualified doctors and hospitals.",
  },
  categories: {
    title: "Cardiac Treatment Areas",
    note: "Treatment areas that may be available through relevant partner hospitals, subject to specialist evaluation. Not every hospital offers every treatment.",
    items: [
      { title: "Coronary Artery Disease", desc: "Evaluation and management of blocked or narrowed coronary arteries." },
      { title: "Angioplasty / PCI", desc: "Catheter-based procedures to open blocked arteries." },
      { title: "Bypass Surgery (CABG)", desc: "Surgical rerouting of blood flow around blocked arteries." },
      { title: "Valve Treatment & Replacement", desc: "Repair or replacement of damaged heart valves." },
      { title: "TAVR / Transcatheter Valve Procedures", desc: "Minimally invasive valve replacement via catheter." },
      { title: "Electrophysiology", desc: "Diagnosis and treatment of heart rhythm disorders." },
      { title: "Pacemaker & ICD Procedures", desc: "Implantable devices to manage heart rhythm." },
      { title: "Arrhythmia Treatment", desc: "Management of irregular heartbeats, including ablation where appropriate." },
      { title: "Structural Heart Disease", desc: "Evaluation and treatment of structural heart conditions." },
      { title: "Heart Failure Evaluation", desc: "Assessment and management of heart failure." },
      { title: "Pediatric Cardiac Surgery", desc: "Cardiac surgical care for children with heart conditions." },
      { title: "Cardiac Diagnostics & Second Opinions", desc: "Specialist review of existing reports and diagnoses." },
    ],
  },
  doctorsSection: {
    title: "Meet the Cardiac Specialists",
    subtitle: "Real, verified specialists from our partner hospital network.",
    expertiseLabel: "Focus area",
    cta: "Share Reports for Review",
  },
  hospitalsSection: {
    title: "Cardiac Care at Leading Hospitals in India",
    infoLabel: "Hospital information",
  },
  education: {
    title: "Understanding Heart & Cardiac Treatment",
    disclaimer:
      "Information on this page is for general educational purposes and does not replace medical advice or diagnosis from a qualified healthcare professional.",
    blocks: [
      {
        h: "What is cardiac treatment?",
        p: "Depending on the condition, cardiac treatment may include medication, minimally invasive catheter-based procedures, surgery, monitoring, or rehabilitation.",
      },
      {
        h: "When might a specialist evaluation be needed?",
        p: "Symptoms such as chest discomfort, breathlessness, palpitations, or a known heart condition are often reasons patients seek a cardiac specialist's evaluation.",
      },
      {
        h: "Common cardiac procedures",
        p: "These can range from angioplasty and bypass surgery (CABG) to valve procedures, electrophysiology procedures, and pacemaker/ICD implantation — the right option depends on your specific diagnosis.",
      },
      {
        h: "Why patients consider India",
        p: "Patients often look to India for specialist access, hospital infrastructure, and a wide range of treatment options — alongside coordinated support for international patients.",
      },
      {
        h: "Why medical evaluation matters",
        p: "Every case is different. A qualified specialist needs to review your reports and history before any treatment plan or recommendation can be made.",
      },
    ],
  },
  cost: {
    title: "How Much Does Cardiac Treatment Cost in India?",
    body: "Total cost may depend on several factors, including:",
    factors: [
      "Diagnosis",
      "Procedure type",
      "Complexity",
      "Implant/device requirements",
      "Hospital",
      "Surgeon/specialist",
      "ICU stay",
      "Investigations",
      "Medicines",
      "Length of stay",
      "Rehabilitation/follow-up",
    ],
    fallback: "Share your medical reports to request an individualized treatment estimate.",
    cta: "Request a Treatment Estimate",
  },
  reports: {
    title: "What Should You Share With Us?",
    body: "Share the reports you already have. Our coordination team will let you know if anything additional is needed.",
    examples: ["ECG", "Echocardiogram", "Angiography", "CT coronary angiography", "Cardiac MRI", "Stress test reports", "Blood test results", "Previous discharge summaries", "Prior cardiac procedure reports", "Medication list"],
    uploadLabel: "Upload files or drag and drop",
    uploadHint: "PDF, JPG, PNG, HEIC, TIFF, DOC, XLS — up to 50MB per file, max 5 files",
    privacy: "Your reports are sent securely and are never made publicly accessible.",
  },
  support: {
    title: "Support Beyond the Hospital",
    before: {
      title: "Before Travel",
      items: ["Case coordination", "Appointment coordination", "Hospital communication", "Treatment information", "Travel/visa guidance where applicable"],
    },
    during: {
      title: "During Treatment",
      items: ["Patient coordination", "Communication support", "Local assistance where available", "Family/accompanying-person guidance"],
    },
    after: {
      title: "After Treatment",
      items: ["Follow-up coordination", "Document coordination", "Remote communication support where available"],
    },
    note: "TrueCare coordinates your journey; it does not provide medical treatment itself.",
  },
  faqTitle: "Frequently Asked Questions",
  faqs: [
    { q: "How much does cardiac treatment cost in India?", a: "Cost depends on the diagnosis, procedure type, complexity, and hospital. Share your medical reports to request an individualized estimate." },
    { q: "What reports should I share?", a: "Share the reports you already have, such as ECG, echo, or angiography results. Our team will let you know if anything additional is needed." },
    { q: "Can I get a second opinion from an Indian cardiac specialist?", a: "Yes. Sharing your existing reports allows a specialist to review your case and provide their perspective." },
    { q: "How quickly can my case be reviewed?", a: "Once your reports are submitted, our patient coordination team reviews the information and aims to follow up promptly with next steps." },
    { q: "Can I travel with a family member?", a: "Yes, many patients travel with a family member or companion. We can share general guidance on travel and stay arrangements." },
    { q: "How long might I need to stay in India?", a: "This varies by procedure and recovery needs. Your treating team will confirm an estimated timeline after reviewing your case." },
    { q: "Can TrueCare help with hospital coordination?", a: "Yes, TrueCare coordinates your case with the relevant hospital and specialist team, though clinical decisions are made by the hospital's doctors." },
    { q: "Can my existing cardiologist share reports with the Indian hospital?", a: "Yes, you or your existing cardiologist can share reports with us, and we'll coordinate them with the relevant specialist team." },
    { q: "What happens after I submit my reports?", a: "Our patient coordination team reviews the information you've shared and reaches out regarding next steps, which may include a request for additional information." },
    { q: "Can I speak to someone on WhatsApp?", a: "Yes. You can chat with TrueCare on WhatsApp at any time using the button on this page." },
  ],
  finalCta: {
    headline: "Looking for Cardiac Treatment in India?",
    sub: "Share your medical reports and let TrueCare help coordinate the next steps with the relevant hospital and specialist team.",
    primary: "Share Medical Reports",
    secondary: "Chat on WhatsApp",
  },
  whatsappFloat: "Chat with TrueCare",
  reportForm: {
    fields: {
      name: "Full Name",
      whatsapp: "WhatsApp Number",
      email: "Email (optional)",
      age: "Patient Age",
      timeline: "Preferred Treatment Timeline",
      condition: "Briefly describe the heart condition, symptoms, previous diagnosis, or treatment you have been advised.",
      reports: "Upload Medical Reports",
    },
    placeholders: {
      name: "Your full name",
      whatsapp: "+880 1XXXXXXXXX",
      email: "you@example.com",
      age: "e.g. 58",
      timeline: "e.g. Within 1 month, Flexible",
      condition: "Briefly describe the heart condition, symptoms, or prior diagnosis",
    },
    requiredLegend: "Fields marked with * are required.",
    uploadLabel: "Upload files or drag and drop",
    uploadHint: "PDF, JPG, PNG, HEIC, TIFF, DOC, XLS — up to 50MB per file, max 5 files",
    privacyNotice: "Your reports are sent securely and are never made publicly accessible.",
    submit: "Submit My Reports",
    submitting: "Submitting...",
    uploading: "Uploading reports...",
    successTitle: "Thank you. We've received your request.",
    successBody: "Our patient coordination team will review the information provided and contact you regarding the next steps.",
    continueOnWhatsapp: "Continue on WhatsApp",
    whatsappPrefill: "Hello TrueCare, I have submitted my reports regarding cardiac treatment in India. My name is {name}.",
    disclaimer: "Your information is used only to coordinate your care and is never shared with third parties for marketing purposes.",
    errors: {
      name: "Please enter your name.",
      whatsapp: "Please enter a WhatsApp number with country code.",
      whatsappFormat: "That doesn't look like a valid WhatsApp number. Include your country code, e.g. +880 1XXXXXXXXX.",
      condition: "Please briefly describe the condition.",
      fileSize: '"{name}" is larger than the 50MB limit.',
      uploadFailed: 'Upload failed for "{name}". Please check your connection and try again.',
      generic: "Something went wrong. Please try again, or contact us on WhatsApp.",
      captchaRequired: "Please complete the verification check above before submitting.",
    },
  },
} as const;
