export const cardiacReportFormContent = {
  fields: {
    name: "Full Name",
    whatsapp: "WhatsApp Number",
    email: "Email (optional)",
    age: "Patient Age",
    timeline: "Preferred Treatment Timeline",
    condition: "Briefly describe the heart condition, symptoms, previous diagnosis, or treatment you have been advised.",
    reports: "Upload Medical Reports",
  },
  placeholders: {
    name: "Your full name",
    whatsapp: "+968 9XXXXXXX",
    email: "you@example.com",
    age: "e.g. 58",
    timeline: "e.g. Within 1 month, Flexible",
    condition: "Briefly describe the heart condition, symptoms, or prior diagnosis",
  },
  requiredLegend: "Fields marked with * are required.",
  uploadLabel: "Upload files or drag and drop",
  uploadHint: "PDF, JPG, PNG, HEIC, TIFF, DOC, XLS — up to 50MB per file, max 5 files",
  privacyNotice: "Your reports are sent securely and are never made publicly accessible.",
  submit: "Submit My Reports",
  submitting: "Submitting...",
  uploading: "Uploading reports...",
  successTitle: "Thank you. We've received your request.",
  successBody: "Our patient coordination team will review the information provided and contact you regarding the next steps.",
  continueOnWhatsapp: "Continue on WhatsApp",
  whatsappPrefill: "Hello TrueCare, I have submitted my reports regarding cardiac treatment in India. My name is {name}.",
  disclaimer: "Your information is used only to coordinate your care and is never shared with third parties for marketing purposes.",
  errors: {
    name: "Please enter your name.",
    whatsapp: "Please enter a WhatsApp number with country code.",
    whatsappFormat: "That doesn't look like a valid WhatsApp number. Include your country code, e.g. +968 9XXXXXXX.",
    condition: "Please briefly describe the condition.",
    fileSize: '"{name}" is larger than the 50MB limit.',
    uploadFailed: 'Upload failed for "{name}". Please check your connection and try again.',
    generic: "Something went wrong. Please try again, or contact us on WhatsApp.",
    captchaRequired: "Please complete the verification check above before submitting.",
  },
} as const;
